### PR TITLE
Create rock-paper-scissors.py

### PR DESCRIPTION
**Pull request by ikiebe**

### CODE REVIEW

**Comment by ikiebe** [comment]
jjbjhgh

**Comment by Ife-py** [comment]
wetin dey do this one now

**Comment by ikiebe** [comment]
child abuse be very careful

**Comment by Ife-py** [comment]
be like say i don follow you play too much

**Comment by ikiebe** [comment]
still dey play, gimme one code challenge lets work on it

**Comment by Ife-py** [comment]
guy im currently out of ideas currently

**Comment by ikiebe** [comment]
WORK ON THIS:

Write a program that prints the numbers from 1 to 100. But for multiples of three, print Fizz instead of the number, and multiples of five, print Buzz. For numbers that are multiples of both three and five, print FizzBuzz

**Comment by Ife-py** [comment]
guy how far do am for your side make i do my own here

**Pull request merged**
